name: expiresOn
version: "1.0"
description: >
  A modifier that checks for an expiration date, and hides items that have an expiration date
  that is not in the future.
url: https://github.com/beckysoll/statamic-expires-on
developer: Becky Soll
developer_url: www.beckysoll.com
